// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_neighborhood_Rcpp
Rcpp::IntegerVector get_neighborhood_Rcpp(SEXP x, const Rcpp::IntegerVector& v, const Rcpp::CharacterVector& type, SEXP na);
RcppExport SEXP _networkRcppExample_get_neighborhood_Rcpp(SEXP xSEXP, SEXP vSEXP, SEXP typeSEXP, SEXP naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type na(naSEXP);
    rcpp_result_gen = Rcpp::wrap(get_neighborhood_Rcpp(x, v, type, na));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_networkRcppExample_get_neighborhood_Rcpp", (DL_FUNC) &_networkRcppExample_get_neighborhood_Rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_networkRcppExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
